#!/usr/bin/env sh

apfail() {
    fail="$fail\n$2$1$NC"
}

apsucc() {
    succ="$succ\n$2$1$NC"
}

log() {
    printf "%s\n" "$1" >> "$logf"
    printf "%s\n" "$1"
}

logfail() {
    log "$1"
    apfail "$2" "$3"
}

logsucc() {
    log "$1"
    apsucc "$1" "$GREEN"
}

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

logf="archinstall-post.log"

[ "$(id -u)" = 0 ] && { 
    printf "%s\n" "This script must not be run as root."
    exit 1
}

sudo os-prober
sudo grub-mkconfig -o /boot/grub/grub.cfg

cd "$HOME" || exit 1
mkdir -p code documents downloads pictures programs repo

cd "$HOME/repo" || exit 1
git clone "https://aur.archlinux.org/yay.git" yay 
cd yay || exit 1
makepkg -si || { 
    printf "%s\n" "Could not build yay."
    exit 1
}

yay -Syyyu --no-confirm
yay -S --no-confirm - < "$HOME/archinstall-post/pac/pac.arch"

fail=""
succ=""

while read -r i
do
    mtd="$(printf "%s\n" "$i" | awk -F',' '{print $1}')"
    name="$(printf "%s\n" "$i" | awk -F',' '{print $2}')"
    path="$(printf "%s\n" "$i" | awk -F',' '{print $3}')"
    cmd="$(printf "%s\n" "$i" | awk -F',' '{print $4}')"

    printf "Method: %s\nName: %s\nPath: %s\nCommand: %s\n" "$mtd" "$name" "$path" "$cmd"

    case "$mtd" in
        g)
            cd "$HOME/repo" || continue
            [ -d "$path" ] && {
                msg="The repository [$name] already exists under [$path]"
                logfail "$msg" "$i" "$CYAN"
                continue
            }
            git clone "$name" "$path" || {
                msg="Could not clone the repository"
                logfail "$msg" "$i" "$RED"
                log "$msg"
                apfail "$i" "$RED"
                continue
            }
            cd "$path" || continue
            $cmd || {
                msg="Command [$cmd] fail"
                logfail "$msg" "$i" "$RED"
            }
            logsucc "$i"
            break;;
        y)
            yay -S --no-confirm "$name" || {
                msg="yay failed for [$name]"
                logfail "$msg" "$i" "$RED"
            }
            logsucc "$i"
            break;;
        *)
            msg="Could not recognise: [$i]"
            logfail "$msg" "$i" "$PURPLE"
            break;;
    esac
done < "$HOME/archinstall-post/pac/pac.user"

rm -r ~/archinstall-post
