#!/usr/bin/env sh

printf "%s\n" "LC_ALL=en_GB.UTF-8" >> /etc/environment
printf "%s\n" "LANG=en_GB.UTF-8" >> /etc/locale.conf
sed -i -E 's/#(tr_TR|en_GB|en_US).UTF/\1.UTF/' /etc/locale.gen
locale-gen

mkdir /boot/EFI
mount "/dev/$1" /boot/EFI

grub-install --target=x86_64-efi --bootloader-id=grub-uefi --recheck
mkdir -p /boot/grub/locale
cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
grub-mkconfig -o /boot/grub/grub.cfg

mem="$(free -m | grep Mem | awk '{print $2}')"
mem=$((mem + 1))
fallocate -l "$mem"M /swapfile
chmod 600 /swapfile
mkswap /swapfile

printf "%s\n" '/swapfile none swap sw 0 0' >> /etc/fstab

chsh -s /bin/zsh root
printf "%s\n" "root:$2" | chpasswd
useradd -m -g users -G wheel -s /usr/bin/zsh "$3"
printf "%s\n" "$3:$4" | chpasswd

timedatectl set-timezone Turkey
timedatectl set-ntp true
timedatectl set-local-rtc 0
hwclock --systohc

sed -i 's/# %wheel ALL=(ALL) NO/%wheel ALL=(ALL) NO/' /etc/sudoers

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
reflector --verbose --latest 100 --protocol https --protocol rsync --sort rate --save /etc/pacman.d/mirrorlist

cp -r /archinstall/archinstall-post "/home/$3"
chown -R "$3:users" "/home/$3/archinstall-post"
rm -r /archinstall

systemctl enable sshd
systemctl enable NetworkManager
systemctl enable iwd
systemctl enable dhcpcd

exit 0
