#!/usr/bin/env sh

sed -i -e 's/#tr_TR.UTF/tr_TR.UTF/' -e 's/#en_GB.UTF/en_GB.UTF/' /etc/locale.gen
locale-gen

systemctl enable sshd

grub-install --target=x86_64-efi --bootloader-id=grub-uefi --recheck
cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
grub-mkconfig -o /boot/grub/grub.cfg

fallocate -l "$( free | grep Mem | awk '{print $2}' )" /swap
chmod 600 /swap
mkswap /swap

echo '/swap none swap sw 0 0' | tee -a /etc/fstab

umount -a
reboot
