#!/usr/bin/env sh

echo "LC_ALL=en_GB.UTF-8" >> /etc/environment
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf
sed -i -e 's/#tr_TR.UTF/tr_TR.UTF/' -e 's/#en_GB.UTF/en_GB.UTF/' /etc/locale.gen
locale-gen

mkdir /boot/EFI
mount "/dev/$1" /boot/EFI

grub-install --target=x86_64-efi --bootloader-id=grub-uefi --recheck
mkdir -p /boot/grub/locale
cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
grub-mkconfig -o /boot/grub/grub.cfg

mem="$( free -m | grep Mem | awk '{print $2}' )"
mem=$(( mem + 1 ))
fallocate -l "$mem"M /swapfile
chmod 600 /swapfile
mkswap /swapfile

echo '/swapfile none swap sw 0 0' >> /etc/fstab

chsh -s /bin/zsh root
echo "root:$2" | chpasswd
useradd -m -g users -G wheel -s /usr/bin/zsh "$3"
echo "$3:$4" | chpasswd

timedatectl set-ntp true
hwclock --systohc

sed -i 's/# %wheel ALL=(ALL) NO/%wheel ALL=(ALL) NO/' /etc/sudoers

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
reflector --verbose --latest 1000 --protocol https --protocol http --protocol ftp --sort rate --save /etc/pacman.d/mirrorlist

cp -r /archinstall/archinstall-post "/home/$3"
chown -R "$3:users" "/home/$3/archinstall-post"
rm -r /archinstall

systemctl enable sshd
systemctl enable NetworkManager

exit 0
